In [22]:
import cv2 
import numpy as np
import matplotlib.pyplot as plt 
import face_recognition
import os
import datetime

In [23]:
path = 'Images_attendance'
images = []
ClassName =  []
myList = os.listdir(path)
print(myList)

['Ahmed.jpg', 'Bill.jpeg', 'Elon.jpeg']


In [24]:
for cls in myList:
    current_Img = cv2.imread(f'{path}/{cls}')
    images.append(current_Img)
    ClassName.append(os.path.splitext(cls)[0])
    
print(ClassName)

['Ahmed', 'Bill', 'Elon']


In [25]:



def findEncodings(images):
    encodeList = []
    for img in images:
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
        encode = face_recognition.face_encodings(img)[0]
        encodeList.append(encode)
    return encodeList

def markAttendance(name):
    with open('Attendance.csv', 'r+') as f:
        myDataList = f.readlines()
        nameList = []
        print(myDataList)
        for line in myDataList:
            entry = line.split(',')
            nameList.append(entry[0])
        if name not in nameList:
            now = datetime.datetime.now()
            dtString = now.strftime('%H:%M:%S')
            f.writelines(f'\n{name},{dtString}')



encodeListKnown = findEncodings(images)
print('Encoding Complete')
print(len(encodeListKnown))

Encoding Complete
3


### Notes
In this code there will be a result for each class you have, in a shape of a list contains the distances.
So you pick the least distance and this is what matches you best

In [ ]:
cap = cv2.VideoCapture(0)

while True: 
    success, img = cap.read()
    imgS = cv2.resize(img, (0, 0), None, 0.25, 0.25) #Resize the image to 1/4 size
    imgS = cv2.cvtColor(imgS, cv2.COLOR_BGR2RGB) #Convert the image to RGB
    facesCurFrame = face_recognition.face_locations(imgS) #Find the face locations in the current frame
    encodesCurFrame = face_recognition.face_encodings(imgS, facesCurFrame) #Find the encodings of the current frame

    for encodeFace, faceLoc in zip(encodesCurFrame, facesCurFrame):
        matches = face_recognition.compare_faces(encodeListKnown, encodeFace)
        faceDis = face_recognition.face_distance(encodeListKnown, encodeFace)   
        print(faceDis)
        matchIndex = np.argmin(faceDis) #Find the index of the minimum distance
        if matches[matchIndex]:
            name = ClassName[matchIndex].upper()
            print(name)
            y1, x2, y2, x1 = faceLoc
            y1, x2, y2, x1 = y1*4, x2*4, y2*4, x1*4 #Scale the face location back to the original size
            cv2.rectangle(img, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.rectangle(img, (x1, y2 - 35), (x2, y2), (0, 255, 0), cv2.FILLED) #Draw a filled rectangle for the name
            cv2.putText(img, name, (x1 + 6, y2 - 6), cv2.FONT_HERSHEY_COMPLEX, 1, (255, 255, 255), 2)
            markAttendance(name) #Mark attendance for the recognized face
    cv2.imshow('Webcam', img) #Show the webcam image
    cv2.waitKey(1) #Wait for 1 millisecond
    if cv2.waitKey(1) & 0xFF == ord('q'):
        cv2.destroyAllWindows() #Destroy all windows
        break #Break the loop


[0.56527293 0.91243919 0.8696319 ]
AHMED
['Name,Time\n']
[0.54903979 0.89824011 0.88763626]
AHMED
['Name,Time\n', '\n', 'AHMED,22:58:23']
[0.53012943 0.90554344 0.86365088]
AHMED
['Name,Time\n', '\n', 'AHMED,22:58:23']
[0.55333112 0.92836338 0.90801651]
AHMED
['Name,Time\n', '\n', 'AHMED,22:58:23']
[0.60707333 0.91216245 0.92657601]
[0.53563316 0.91857165 0.9415766 ]
AHMED
['Name,Time\n', '\n', 'AHMED,22:58:23']
[0.54211297 0.91668071 0.93709291]
AHMED
['Name,Time\n', '\n', 'AHMED,22:58:23']
[0.55412263 0.90276265 0.91921022]
AHMED
['Name,Time\n', '\n', 'AHMED,22:58:23']
[0.54899279 0.90286611 0.91208161]
AHMED
['Name,Time\n', '\n', 'AHMED,22:58:23']
[0.59902226 0.92504828 0.94609819]
AHMED
['Name,Time\n', '\n', 'AHMED,22:58:23']
[0.52778881 0.9115785  0.93324569]
AHMED
['Name,Time\n', '\n', 'AHMED,22:58:23']
[0.50544695 0.91876185 0.93453111]
AHMED
['Name,Time\n', '\n', 'AHMED,22:58:23']
[0.51168572 0.89699919 0.92442998]
AHMED
['Name,Time\n', '\n', 'AHMED,22:58:23']
[0.5412229  0.924

KeyboardInterrupt: 

: 